ALTER TABLE orders ADD COLUMN full_name VARCHAR(150) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN dni       VARCHAR(20)  NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN address   TEXT         NOT NULL DEFAULT '';